server:
  port: 9097

spring:

  application:
    name: users-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  secret: ${JWT_SECRET}

service-urls:
  discount-service-url: ${DISCOUNT_SERVICE_URL}
  cart-service-url: ${CART_SERVICE_URL}

logging:
  level:
    root: INFO

    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.web.authentication: TRACE

    org.springframework.web.filter: TRACE

    org.webapp.ecommerce: TRACE

    org.springframework.security.authorization.method: TRACE

known-services:
  allowed-services:
    - cart-service
    - discount-service