server:
  port: ${API_GATEWAY_PORT}

spring:

  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3001"
              - "http://localhost:3002"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: false
      server:
        webflux:
          routes:
            # Route 1: Cart-Service
            - id: cart-service
              uri: ${CART_SERVICE_URI}
              predicates:
                - Path=/api/cart/**
              filters:
                # Add a header to the request
                - AddRequestHeader=X-Gateway, true

                # Add a header to the response
                - AddResponseHeader=X-Response-Time, 100ms

                # Limit request size (protect your service)
                - RequestSize=5MB

                # Retry failed requests
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY

            # Route 2: Discount-Service
            - id: discount-service
              uri: ${DISCOUNT_SERVICE_URI}
              predicates:
                - Path=/api/coupon/**

            # Route 3: Inventory-Service
            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URI}
              predicates:
                - Path=/api/inventory/**

            # Route 4: Order-Service
            - id: order-service
              uri: ${ORDER_SERVICE_URI}
              predicates:
                - Path=/api/orders/**

            # Route 5: Products-Service
            - id: products-service
              uri: ${PRODUCTS_SERVICE_URI}
              predicates:
                - Path=/api/categories/**,/api/products/**

            # Route 6: Users-Service
            - id: users-service
              uri: ${USERS_SERVICE_URI}
              predicates:
                - Path=/api/users/**

            # Route 7: Users-Service
            - id: auth-service
              uri: ${USERS_SERVICE_URI}
              predicates:
                - Path=/api/auth/**

            # Route 8: Payment-Service
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI}
              predicates:
                - Path=/api/payments/**

jwt:
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO

    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.web.authentication: TRACE

    org.springframework.web.filter: TRACE

    org.webapp.ecommerce: TRACE

    org.springframework.security.authorization.method: TRACE