server:
  port: ${PAYMENT_SERVICE_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  service-secret: ${JWT_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key : ${STRIPE_WEBHOOK_SECRET}

known-services:
  allowed-services:
    - order-service

logging:
  level:
    org.springframework.security: DEBUG

service-urls:
  order-service-url: ${ORDER_SERVICE_URL}