CREATE DATABASE IF NOT EXISTS users_service;
CREATE DATABASE IF NOT EXISTS products_service;
CREATE DATABASE IF NOT EXISTS cart_service;
CREATE DATABASE IF NOT EXISTS inventory_service;
CREATE DATABASE IF NOT EXISTS order_service;
CREATE DATABASE IF NOT EXISTS payment_service;
CREATE DATABASE IF NOT EXISTS discount_service;