server:
  port: ${ORDER_SERVICE_PORT}

spring:

  application:
    name: order-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  service-secret: ${JWT_SECRET}

service-urls:
  cart-service-url: ${CART_SERVICE_URL}
  discount-service-url: ${DISCOUNT_SERVICE_URL}
  inventory-service-url: ${INVENTORY_SERVICE_URL}
  products-service-url: ${PRODUCTS_SERVICE_URL}
  payment-service-url: ${PAYMENT_SERVICE_URL}
  users-service-url: ${USERS_SERVICE_URL}

logging:
  level:
    root: INFO

    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.web.authentication: TRACE

    org.springframework.web.filter: TRACE

    org.webapp.ecommerce: TRACE

    org.springframework.security.authorization.method: TRACE

known-services:
  allowed-services:
    - inventory-service
    - cart-service
    - discount-service
    - products-service
    - payment-service
    - users-service

payment:
  currencyCode: INR